POST https://8412-102-89-44-26.ngrok-free.app/user/signup
Content-Type: application/json

{
    "first_name":"John",
    "last_name":"Ayilara",
    "email":"amjaystar@gmail.com",
    "password":"Johnpank1",
    "phone": "090225363843",
    "transaction_pin":"2340",
    "tag": "Jaystar"
}
