POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "first_name":"John",
    "last_name":"Ayilara",
    "email":"amjaystar@gmail.com",
    "password":"Johnpank1",
    "phone": "09026381029",
    "transaction_pin":"1000",
    "tag": "Jaystar"
}
