GET http://localhost:8080/wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHBpcmVkQXQiOjE3MTIxNzI3NDEsImVtYWlsIjoiamJheWlsYXJhQGdtYWlsLmNvbSIsInVzZXJJZCI6MX0.P1zzBwbeDEusIA8T3GDa2N_KwkEzhlLHNt-s4fkjSmM